### ISSUE TITLE
Cam Fici Top charts and Record Sales

### ISSUE THREAD

**Issue by Ficicabhs** [choibhs/fall2019#11]

**Comment by Ficicabhs** [comment]
two days

**Comment by choibhs** [comment]
Still working through Git setup. Starting first page today.

**Comment by choibhs** [comment]
Needs to make table and put info in. Wasn't able to get Ubuntu installed.

**Comment by choibhs** [comment]
Integrated via cherry-picking (not part of a pull request; not sure what happened with that)
