### ISSUE TITLE
First Version of Football Teams and Highlights

### ISSUE THREAD

**Issue by cooperrobhs** [choibhs/fall2019#12]

**Comment by cooperrobhs** [comment]
Time estimated: 2 school days

**Comment by choibhs** [comment]
Bobby hasn't started his page yet and needs to catch up

**Comment by choibhs** [comment]
Still organizing first page and has added table. A little behind.

**Comment by choibhs** [comment]
Integrated via pull request https://github.com/choibhs/fall2019/pull/28
