### ISSUE TITLE
Jack Farrell High School Football commits and NFL Draft Top 10

### ISSUE THREAD

**Issue by farrelljabhs** [choibhs/fall2019#14]

**Comment by farrelljabhs** [comment]
Due in 2 school days.

**Comment by choibhs** [comment]
Hasn't started work on his page yet, so needs to catch up

**Comment by choibhs** [comment]
Finished first page with drop-down menu and has added info about most players. Has added styling, but no JS yet.

**Comment by choibhs** [comment]
Closed under pull request https://github.com/choibhs/fall2019/pull/29
