### ISSUE TITLE
Jack Dyer records and standings

### ISSUE THREAD

**Issue by dyerjabhs** [choibhs/fall2019#4]

**Comment by dyerjabhs** [comment]
two school days (four normal ones)

**Comment by choibhs** [comment]
Was records and standings but is now standings and highlights. Has created two tables. On track.

**Comment by choibhs** [comment]
Version of first page without JS but with styling.

**Comment by choibhs** [comment]
Closed under pull request https://github.com/choibhs/fall2019/pull/21
