### ISSUE TITLE
Eli Goldstein: How Spikeball started and where it's headed

### ISSUE THREAD

**Issue by goldsteinelbhs** [choibhs/fall2019#6]

**Comment by goldsteinelbhs** [comment]
TIME ESTIMATE IS TWO DAYS DUE  WEDNESDAY NOVEMBER 13th

**Comment by choibhs** [comment]
On track

**Comment by choibhs** [comment]
Finished with styling and one JS function. Still having issue with font size.

**Comment by choibhs** [comment]
Closed under pull request https://github.com/choibhs/fall2019/pull/27
