### ISSUE TITLE
Freddy Pimental-First Version of Spikeball Main Page

### ISSUE THREAD

**Issue by pimentalfrbhs** [choibhs/fall2019#7]

**Comment by pimentalfrbhs** [comment]
Time estimated 2 days

**Comment by choibhs** [comment]
On track

**Comment by choibhs** [comment]
Finished his intro page inc. JS and styling. Needs to link to the other group members pages.

**Comment by choibhs** [comment]
Closed under pull request https://github.com/choibhs/fall2019/pull/23
